[package]
    edition = "2024"
    name    = "wally"
    version = "0.4.4"

[dependencies]
    clap         = { version = "4.5.53", features = ["cargo", "derive"] }
    image        = "0.25.9"
    noise_perlin = "1.0.0"
    rand         = { version = "0.9.2", features = ["small_rng"] }
    rayon        = "1.11.0"

[profile.release]
    codegen-units = 1
    lto           = "thin"
    opt-level     = 3
    panic         = "abort"
