[package]
    authors = ["Joaquín Zúñiga <jp.zuniga.dev@gmail.com>"]
    categories = ["Graphics"]
    description = "Elegant, minimal, and sleek wallpaper generator."
    edition = "2024"
    exclude = [
        ".github/",
        ".gitignore",
        "docs/",
        "rustfmt.toml",
        "shell.nix",
    ]
    keywords = ["cli", "random", "wallpapers"]
    license = "GPL-3.0-or-later"
    name = "wally-rs"
    readme = "README.md"
    repository = "https://github.com/jp-zuniga/wally"
    version = "0.5.3"

[dependencies]
    clap         = { version = "4.5.53", features = ["cargo", "derive"] }
    colored      = "3.0.0"
    image        = "0.25.9"
    noise_perlin = "1.0.0"
    rand         = { version = "0.9.2", features = ["small_rng"] }
    rayon        = "1.11.0"

[profile.release]
    codegen-units = 1
    lto           = "thin"
    opt-level     = 3
    panic         = "abort"

[[bin]]
    name = "wally"
    path = "src/main.rs"
